version: "3.5"
services:

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
      - "8389:8389"
    env_file:
      - .env
    secrets:
      - my_secret

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db_example

secrets:
  my_secret:
    file: ./secret_data